SET NAMES UTF8;
DROP DATABASE IF EXISTS ifeng;
CREATE DATABASE ifeng CHARSET=utf8;
USE ifeng;
CREATE TABLE t_news(
	nid INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(20),
	content VARCHAR(500),
	count BIGINT,
	pubtime DATETIME
);
